import { createFileRoute, Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { BrainCircuit, Database, GitBranch, Lightbulb, ArrowRight } from "lucide-react";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "How It Works — Smart Tech Buy Advisor" },
      { name: "description", content: "Learn how our SWI-Prolog knowledge-based expert system reasons about devices." },
      { property: "og:title", content: "How It Works — Smart Tech Buy Advisor" },
      { property: "og:description", content: "A real Prolog inference engine powers every recommendation." },
    ],
  }),
  component: About,
});

const pillars = [
  {
    icon: Database,
    title: "Knowledge Base",
    body: "Laptops and phones are stored as Prolog facts (laptops.pl, mobiles.pl) describing CPU, RAM, GPU, battery, camera and capability tags.",
  },
  {
    icon: GitBranch,
    title: "Rules & Inference",
    body: "rules.pl derives desired capabilities from your answers, filters by budget, scores each device and ranks them — purely with Prolog logic.",
  },
  {
    icon: BrainCircuit,
    title: "Reasoning Engine",
    body: "Tau Prolog runs the program in your browser, asserting your answers as user_pref/2 facts and resolving the recommend/7 query.",
  },
  {
    icon: Lightbulb,
    title: "Explainable Results",
    body: "Each suggestion comes with human-readable reasons generated by Prolog rules, so you always know why a device was chosen.",
  },
];

function About() {
  return (
    <main className="relative min-h-screen grid-bg px-6 py-12">
      <div className="mx-auto max-w-4xl">
        <span className="glass rounded-full px-4 py-1.5 text-xs font-medium text-primary">
          ⚡ Powered by SWI-Prolog logic
        </span>
        <h1 className="font-display mt-5 text-3xl font-black sm:text-4xl">
          An honest <span className="text-gradient">expert system</span>
        </h1>
        <p className="mt-4 max-w-2xl text-muted-foreground">
          Unlike black-box AI, every recommendation here is produced by a transparent
          knowledge base and a logic-based inference engine. The website is only the
          interface — the intelligence lives entirely in Prolog.
        </p>

        <div className="mt-10 grid gap-5 sm:grid-cols-2">
          {pillars.map((p, i) => (
            <motion.div
              key={p.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.08 }}
              className="glass rounded-2xl p-6"
            >
              <p.icon className="h-8 w-8 text-primary" />
              <h3 className="font-display mt-4 text-lg font-semibold">{p.title}</h3>
              <p className="mt-2 text-sm text-muted-foreground">{p.body}</p>
            </motion.div>
          ))}
        </div>

        <div className="mt-10 glass rounded-2xl p-6">
          <h2 className="font-display text-lg font-bold">The pipeline</h2>
          <pre className="mt-3 overflow-x-auto rounded-lg bg-background/60 p-4 text-xs text-muted-foreground">
{`Your answers ─▶ user_pref/2 facts
            ─▶ desired/1   (derive needed capabilities)
            ─▶ budget_limit (filter by price)
            ─▶ total_score  (rank candidates)
            ─▶ recommend/7  (top 5 + reasons)`}
          </pre>
        </div>

        <div className="mt-10">
          <Link
            to="/advisor"
            className="bg-gradient-hero inline-flex items-center gap-2 rounded-xl px-6 py-3 font-semibold text-primary-foreground glow"
          >
            Try the Advisor <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    </main>
  );
}
